CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    DIRECCION VARCHAR(100),
    ESTADO CHAR(1) DEFAULT 'A'  -- 'A' = Activo, 'I' = Inactivo
);

CREATE TABLE FACTURAS (
    ID_FACTURA INT PRIMARY KEY,
    ID_USUARIO INT,
    MONTO DECIMAL(10,2),
    DESCUENTO DECIMAL(5,2),
    FEC_FACTURA DATE,
    ESTADO CHAR(1), -- 'P' = Pagada, 'D' = Deuda, 'E' = Eliminada
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

INSERT ALL
  INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, DIRECCION) VALUES (1, 'Ana', 'Ramírez', 'San José')
  INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, DIRECCION) VALUES (2, 'Luis', 'Cordero', 'Alajuela')
  INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, DIRECCION) VALUES (3, 'Marta', 'Jiménez', 'Cartago')
  INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, DIRECCION) VALUES (4, 'Carlos', 'Rojas', 'Heredia')
SELECT * FROM DUAL;

INSERT ALL
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (1, 1, 900, 0, TO_DATE('2024-12-01', 'YYYY-MM-DD'), 'D')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (2, 1, 1500, 100, TO_DATE('2024-12-02', 'YYYY-MM-DD'), 'P')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (3, 2, 800, 0, TO_DATE('2024-12-03', 'YYYY-MM-DD'), 'D')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (4, 2, 1200, 50, TO_DATE('2024-12-04', 'YYYY-MM-DD'), 'P')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (5, 3, 1000, 0, TO_DATE('2024-12-05', 'YYYY-MM-DD'), 'P')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (6, 3, 500, 0, TO_DATE('2024-12-06', 'YYYY-MM-DD'), 'E')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (7, 4, 700, 0, TO_DATE('2024-12-07', 'YYYY-MM-DD'), 'D')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (8, 4, 1100, 100, TO_DATE('2024-12-08', 'YYYY-MM-DD'), 'P')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (9, 1, 950, 50, TO_DATE('2024-12-09', 'YYYY-MM-DD'), 'P')
  INTO FACTURAS (ID_FACTURA, ID_USUARIO, MONTO, DESCUENTO, FEC_FACTURA, ESTADO) VALUES (10, 2, 1300, 150, TO_DATE('2024-12-10', 'YYYY-MM-DD'), 'P')
SELECT * FROM DUAL;

DELETE FROM FACTURAS
WHERE MONTO < 1000;
